export const SET_IMG_SRC_AND_FILE_OBJ_TO_REDUCER = 'setImgSrcToReducer';


export const DELETE_ONE_ImgSrc_AND_ONE_ImgFile = 'deleteOneImgSrcAndOneImgFile';

export const REVOKE_OBJECT_URL_IN_ACTION_CREATOR_TO_MAKE_COMPONENT_PURE = 'revokeObjectURLInActionCreatorToMakeComponentPure';

export const WHEN_SHOP_INIT_MEAL_LIST_INSERT_DONE = 'when_shop_init_meal_list_insert';

export const REMOVE_ThoseFileArrAndObjectURLArr_but_also_returnObjectUrlArr_to_RevokeObjectURL = 'removeThoseFileArrAndObjectURLArr_but_also_returnObjectUrlArr_to_RevokeObjectURL';