export const JOIN_ORDER_FETCH_INIT_DATA_RESULT = 'JOIN_ORDER_FETCH_INIT_DATA_RESULT';

export const JOIN_ORDER_MAKE_ORDER_RESULT = 'JOIN_ORDER_MAKE_ORDER_RESULT';

export const JOIN_ORDER_ORDER_I_MAKE_FROM_INIT_FETCH_ORDER = 'JOIN_ORDER_ORDER_I_MAKE_FROM_INIT_FETCH_ORDER';


export const CHANGE_OTHERS_ORDER_FROM_INIT_FETCH = 'CHANGE_OTHERS_ORDER_FROM_INIT_FETCH';


export const AFTER_DELETE_SELF_ORDERED_MEAL_SUCCESS = 'AFTER_DELETE_SELF_ORDERED_MEAL_SUCCESS';