export const VENDOR_DATA_WHEN_MAKE_ORDER = 'VENDOR_DATA_WHEN_MAKE_ORDER';

export const CHOOSED_VENDOR_DATA_WHEN_MAKE_ORDER_CONFIRM = 'CHOOSED_VENDOR_DATA_WHEN_MAKE_ORDER_CONFIRM';


export const WHEN_INSERT_ORDER_COMPLETE = 'WHEN_INSERT_ORDER_COMPLETE';